### ISSUE TITLE
RenderCrash

### ISSUE THREAD

**Issue by ghost** [UnwrittenFun/ImmersiveIntegration#55] opened 2015-12-06 12:25 UTC
Crashing while switching creative menu pages.
http://pastebin.com/9eXUpT8L

**Comment by artdude543** [comment] 2015-12-06 13:24
Can't reproduce this issue, or see how it's this mods fault. Can you be more specific on what you was doing to get this crash? I.E. Was this a one off or can you get this to happen all the time?

**Comment by Voxel-Friend** [comment] 2015-12-06 13:31
Can confirm with latest version released 2 days ago, 0.6.3. My guess, it has to do with the new extendable post replacing the old extended post, which was used for the creative tab.
Mod list Via Data dump: http://pastebin.com/LRF57GQ2
Crash Report identical to @BobZplus.

**Comment by cadaverous-eris** [comment] 2015-12-07 05:04
same problem here

**Comment by jamesbirtles** [comment] 2015-12-07 15:25
Can anyone give any more information on this, how can I reproduce it?
Right now I have no clue why this is happening, nor can I make it happen myself.

**Comment by cadaverous-eris** [comment] 2015-12-07 22:21
Happens every time I open the creative inventory and switch to the page that shows the immersive integration tab. The problem appears to be that the item you set for the creative tab icon doesn't exist.

**Comment by jamesbirtles** [comment] 2015-12-08 00:02
I haven't removed any items and the item set as the tab icon is fluix wire coil as shown here: https://github.com/UnwrittenFun/ImmersiveIntegration/blob/fix-ae/src/main/java/unwrittenfun/minecraft/immersiveintegration/ImmersiveIntegration.java#L38

**Comment by cadaverous-eris** [comment] 2015-12-08 05:20
Ooooohhhhh...... that makes so much sense. I have a feeling you'd be able to reproduce the crash if you tested it without AE, if you catch my drift (I don't use AE, so your fluix wire coil wasn't initialized in my minecraft instance).

**Comment by jamesbirtles** [comment] 2015-12-08 05:21
Oh crap yeah, I will release a fix later today

**Comment by jamesbirtles** [comment] 2015-12-08 12:58
Should be fixed in 0.6.4, thanks for the reports
http://minecraft.curseforge.com/projects/immersive-integration/files/2269884

**Closed as completed by jamesbirtles** 2015-12-08 12:58 UTC
